import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { AppSidebar } from "@/components/providers/app-sidebar";
import { QueryClientProvider } from "@/components/providers/query-client-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
			>
				<QueryClientProvider>
					<SidebarProvider className="bg-sidebar p-4 overflow-hidden h-dvh">
						<AppSidebar />
						<ThemeProvider
							attribute="class"
							defaultTheme="system"
							enableSystem
							disableTransitionOnChange
						>
							<main className="h-full min-h-dvh w-full flex flex-col bg-background overflow-hidden rounded-md relative">
								<SidebarTrigger className="absolute top-4 left-4" />
								{children}
								<Toaster />
							</main>
						</ThemeProvider>
					</SidebarProvider>
				</QueryClientProvider>
			</body>
		</html>
	);
}
